// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt6sj2fGevkn2tA-xXaNSnIa5qViwpZ9s',
    appId: '1:929239288066:web:76b98d5ab1551c70e15a1b',
    messagingSenderId: '929239288066',
    projectId: 'saraswaticosmeticapp',
    authDomain: 'saraswaticosmeticapp.firebaseapp.com',
    storageBucket: 'saraswaticosmeticapp.appspot.com',
    measurementId: 'G-QBPMYM4XWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4Tg8wbPEWDfZO0D9EK8PnE9qaQPKUTMM',
    appId: '1:929239288066:android:2327748ce09d3f69e15a1b',
    messagingSenderId: '929239288066',
    projectId: 'saraswaticosmeticapp',
    storageBucket: 'saraswaticosmeticapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9zhIBFeZCh3SjIMBueD7KiPD87Mm4Iwg',
    appId: '1:929239288066:ios:01d9aa07b4466e82e15a1b',
    messagingSenderId: '929239288066',
    projectId: 'saraswaticosmeticapp',
    storageBucket: 'saraswaticosmeticapp.appspot.com',
    androidClientId: '929239288066-8tmf122v4jlf2h55b1lb3cpqlgmgjd4r.apps.googleusercontent.com',
    iosClientId: '929239288066-qb9go2o82ck8tc3f94ia8519vfuc70bp.apps.googleusercontent.com',
    iosBundleId: 'com.example.saraswatiApplicationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9zhIBFeZCh3SjIMBueD7KiPD87Mm4Iwg',
    appId: '1:929239288066:ios:c52df91ba8718f4ae15a1b',
    messagingSenderId: '929239288066',
    projectId: 'saraswaticosmeticapp',
    storageBucket: 'saraswaticosmeticapp.appspot.com',
    androidClientId: '929239288066-8tmf122v4jlf2h55b1lb3cpqlgmgjd4r.apps.googleusercontent.com',
    iosClientId: '929239288066-1ho16ibu20lqdmqk156soql3q0tut6ve.apps.googleusercontent.com',
    iosBundleId: 'com.example.saraswatiApplicationProject.RunnerTests',
  );
}
